
 
 ************ 2020-07-11 12:08:04,530 [34] ERROR App  
     ERROR in src/app/hire-me/services/hire-me.service.ts(43,12): error TS2304: Cannot find name 'HelperCategoryModel'.
    
 ********** 
 

 
 ************ 2020-07-11 12:11:56,952 [34] ERROR App  
     ERROR in src/app/hire-me/services/hire-me.service.ts(43,12): error TS2304: Cannot find name 'HelperCategoryModel'.
    
 ********** 
 

 
 ************ 2020-07-11 12:21:44,218 [34] ERROR App  
     ERROR in src/app/hire-me/hire-me/hire-me.component.ts(80,9): error TS2740: Type 'HelperCategoryDropDownModel' is missing the following properties from type 'HelperCategoryDropDownModel[]': length, pop, push, concat, and 26 more.
    
 ********** 
 

 
 ************ 2020-07-11 12:29:38,022 [19] ERROR App  
     ERROR in src/app/hire-me/hire-me/hire-me.component.ts(80,9): error TS2740: Type 'HelperCategoryDropDownModel' is missing the following properties from type 'HelperCategoryDropDownModel[]': length, pop, push, concat, and 26 more.
    
 ********** 
 

 
 ************ 2020-07-11 12:33:15,406 [19] ERROR App  
     ERROR in src/app/hire-me/hire-me/hire-me.component.ts(80,9): error TS2740: Type 'HelperCategoryDropDownModel' is missing the following properties from type 'HelperCategoryDropDownModel[]': length, pop, push, concat, and 26 more.
    
 ********** 
 

 
 ************ 2020-07-11 12:39:47,029 [19] ERROR App  
     ERROR in src/app/hire-me/hire-me/hire-me.component.ts(80,9): error TS2740: Type 'HelperCategoryDropDownModel' is missing the following properties from type 'HelperCategoryDropDownModel[]': length, pop, push, concat, and 26 more.
    
 ********** 
 

 
 ************ 2020-07-11 12:56:42,664 [19] ERROR App  
     ERROR in src/app/hire-me/hire-me/hire-me.component.ts(80,9): error TS2740: Type 'HelperCategoryDropDownModel' is missing the following properties from type 'HelperCategoryDropDownModel[]': length, pop, push, concat, and 26 more.
    
 ********** 
 

 
 ************ 2020-07-11 12:57:02,561 [19] ERROR App  
     ERROR in src/app/hire-me/hire-me/hire-me.component.ts(66,38): error TS2345: Argument of type 'PaginationBase' is not assignable to parameter of type 'HelperPagination'.
      Type 'PaginationBase' is missing the following properties from type 'HelperPagination': HelperCategoryId, totalRecords, details, extensionData
    src/app/hire-me/hire-me/hire-me.component.ts(80,9): error TS2740: Type 'HelperCategoryDropDownModel' is missing the following properties from type 'HelperCategoryDropDownModel[]': length, pop, push, concat, and 26 more.
    
 ********** 
 

 
 ************ 2020-07-11 13:56:06,936 [19] ERROR App  
     ERROR in src/app/hire-me/services/hire-me.service.ts(28,41): error TS2551: Property 'HelperCategoryId' does not exist on type 'HelperPagination'. Did you mean 'helperCategoryId'?
    src/app/hire-me/hire-me/hire-me.component.ts(98,37): error TS2339: Property 'CategoryIds' does not exist on type 'HelperPagination'.
    src/app/hire-me/hire-me/hire-me.component.ts(100,25): error TS2339: Property 'CategoryIds' does not exist on type 'HelperPagination'.
    src/app/hire-me/hire-me/hire-me.component.ts(103,10): error TS2339: Property 'getProductList' does not exist on type 'HireMeComponent'.
    
 ********** 
 

 
 ************ 2020-07-11 13:57:48,340 [19] ERROR App  
     ERROR in src/app/hire-me/services/hire-me.service.ts(28,41): error TS2551: Property 'HelperCategoryId' does not exist on type 'HelperPagination'. Did you mean 'helperCategoryId'?
    
 ********** 
 

 
 ************ 2020-07-11 19:44:24,746 [17] ERROR App  
 WARNING in Emitted no files.

 ********** 
 

 
 ************ 2020-07-11 22:06:56,257 [20] ERROR App  
 Failed executing DbCommand (401ms) [Parameters=[@p0='?' (Size = 4000), @p1='?' (Size = 4000), @p2='?' (Size = 4000), @p3='?' (Size = 4000), @p4='?' (DbType = DateTime2), @p5='?' (Size = 4000), @p6='?' (DbType = DateTime2), @p7='?' (Size = 450), @p8='?' (DbType = Int32), @p9='?' (Size = 4000), @p10='?' (Size = 450), @p11='?' (Size = 4000), @p12='?' (Size = 1) (DbType = Byte), @p13='?' (Size = 4000), @p14='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Customers] ([AddressLine], [City], [Country], [CreatedById], [CreatedOn], [EditedById], [EditedOn], [Email], [ImageId], [Name], [PhoneNo], [PostalCode], [RecordState], [State], [UserId])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14);
SELECT [Id]
FROM [Customers]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity(); ********** 
 

 
 ************ 2020-07-11 22:06:57,067 [20] ERROR App  
 An exception occurred in the database while saving changes for context type 'Help247.Data.AppDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Customers' with unique index 'IX_Customers_PhoneNo'. The duplicate key value is (0771233625).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:5df35418-d927-4565-90e4-6d1645d94035
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) ********** 
 
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Customers' with unique index 'IX_Customers_PhoneNo'. The duplicate key value is (0771233625).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:5df35418-d927-4565-90e4-6d1645d94035
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

 
 ************ 2020-07-11 22:19:10,494 [22] ERROR App  
 Failed executing DbCommand (408ms) [Parameters=[@p0='?' (Size = 4000), @p1='?' (Size = 50), @p2='?' (Size = 4000), @p3='?' (Size = 4000), @p4='?' (Size = 4000), @p5='?' (DbType = DateTime2), @p6='?' (Size = 4000), @p7='?' (DbType = DateTime2), @p8='?' (Size = 450), @p9='?' (DbType = Int32), @p10='?' (Size = 4000), @p11='?' (DbType = Int32), @p12='?' (DbType = Int32), @p13='?' (Size = 4000), @p14='?' (Size = 450), @p15='?' (Size = 4000), @p16='?' (Size = 450), @p17='?' (Size = 4000), @p18='?' (Size = 1) (DbType = Byte), @p19='?' (Size = 4000), @p20='?' (Size = 4000)], CommandType='Text', CommandTimeout='30']
SET NOCOUNT ON;
INSERT INTO [Helpers] ([AboutMe], [AddressLine], [City], [Country], [CreatedById], [CreatedOn], [EditedById], [EditedOn], [Email], [Experience], [FirstName], [HelperCategoryId], [ImageId], [LastName], [MobileNo], [MyService], [PhoneNo], [PostalCode], [RecordState], [State], [UserId])
VALUES (@p0, @p1, @p2, @p3, @p4, @p5, @p6, @p7, @p8, @p9, @p10, @p11, @p12, @p13, @p14, @p15, @p16, @p17, @p18, @p19, @p20);
SELECT [Id]
FROM [Helpers]
WHERE @@ROWCOUNT = 1 AND [Id] = scope_identity(); ********** 
 

 
 ************ 2020-07-11 22:19:11,303 [22] ERROR App  
 An exception occurred in the database while saving changes for context type 'Help247.Data.AppDbContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Helpers' with unique index 'IX_Helpers_Email'. The duplicate key value is (hisham_89@live.com).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:5db4d26e-e60b-4e26-af1c-03323ff1f423
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken) ********** 
 
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Cannot insert duplicate key row in object 'dbo.Helpers' with unique index 'IX_Helpers_Email'. The duplicate key value is (hisham_89@live.com).
The statement has been terminated.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__164_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
ClientConnectionId:5db4d26e-e60b-4e26-af1c-03323ff1f423
Error Number:2601,State:1,Class:14
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(DbContext _, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

 
 ************ 2020-07-11 23:35:58,530 [4] ERROR App  
     ERROR in src/app/auth/login/login.component.ts(17,19): error TS2304: Cannot find name 'ForgotPasswordModel'.
    src/app/auth/login/login.component.ts(105,31): error TS2304: Cannot find name 'ForgotPasswordModel'.
    
 ********** 
 
